#!/usr/bin/bash

#####
# postrm script
####

set -uo pipefail

# Declaration variables
meoListInstalledPkgsPure="/usr/lib/meo/library/info/list-installed-packages-pure"

if [[ -e "$meoListInstalledPkgsPure" ]]
then
    #
    sed -i "/vimizer/d" "$meoListInstalledPkgsPure" 2> /dev/null
fi

